params:
  base_dir: /Datasets/KITTI/dataset
  sequence: 00
  time_warp_scale: 1.0
  clouds_as_organized_points: false
  publish_lidar: true
  publish_image_0: false
  publish_image_1: false
  publish_image_2: true
  publish_image_3: false
  publish_ground_truth: true